```
#
# try :
#     a = int(input('나누는 수를 정수로 입력하세요'))
#     b = int(input('나누어지는 수를 정수로 입력하시오'))
#     result = b / a      # 예외가 발생할 수 있는 구간이 try 문 내에 있어야만 합니다.
# except ZeroDivisionError as e:
#     print(e)
# except TypeError as e:
#     print(e)
# except ValueError as e:
#     print(e)
# except Exception as e:
#     print(e)
# else:
#     print(f'b/a = { result }')
# finally:
#     print('프로그램종료')

```

결과적으로 개발자가 고려해야할 것은 일단 try를 써버리면 except 안썼을때 오류가 발생
하기 때문에 try / except문이 없는 상태에서 다양하게 검증해보고 어떤 예외가 발생하는지 체크 해야합니다.
그리고 그 발생한 예외들에 대한 except문을 작성해야하고, 정상적으로 처리가 되었을 때 else문을 쓸 
필요가 있을 겁니다.

하지만 이상의 사례와 같이 a =0을 입력하는 것 자체가 예외를 발생시키지 않고,
1. a=0이면서
2. b / a 연산을 시도할 때 ZeroDivisionError가 발생하기 때문에,

else문에 b/aㄱ 가 포함되어서는 안됩니다.
그래서 try문 내에 result = b/a